import CheckIcon from "./CheckIcon"
import FlagIcon from "./FlagIcon"
import InboxIcon from "./InboxIcon"
import KanbanIcon from "./KanbanIcon"
import LayoutDashboardIcon from "./LayoutDashboardIcon"
import MenuIcon from "./MenuIcon"
import PackageIcon from "./PackageIcon"
import SearchIcon from "./SearchIcon"
import SettingsIcon from "./SettingsIcon"
import TeamIcon from "./TeamIcon"
import TimerIcon from "./TimerIcon"
import FilePenIcon from "./FilePenIcon"
import XIcon from "./XIcon"
import CircleCheckIcon from "./CircleCheckIcon"

export {CheckIcon, FlagIcon, InboxIcon, KanbanIcon, LayoutDashboardIcon, MenuIcon, PackageIcon, SearchIcon, SettingsIcon, TeamIcon, TimerIcon, FilePenIcon, CircleCheckIcon, XIcon}